"""Test migration

Revision ID: 04c124c03ce1
Revises: 
Create Date: 2025-12-13 19:32:10.828820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04c124c03ce1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('type_test',
    sa.Column('test_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prompt', sa.String(length=10000), nullable=False),
    sa.Column('time_limit', sa.Integer(), nullable=True),
    sa.Column('words_typed', sa.Integer(), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=False),
    sa.Column('wpm', sa.Float(), nullable=False),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('test_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('type_test')
    # ### end Alembic commands ###
